name: 'Validate PR Title and Body'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write
  statuses: write

jobs:
  validate-pr:
    name: Validate PR Title and Body
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure allowed types based on CONTRIBUTING.md
          types: |
            feat
            fix
            docs
            chore
            style
            refactor
            test
          # Configure that scope is optional but recommended
          requireScope: false
          # Configure subject pattern to ensure proper formatting
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            should start with a lowercase letter and be written in imperative mood.
            Please check the CONTRIBUTING.md for examples.
          # Configure body validation pattern (at least 20 chars, not just whitespace)
          bodyPattern: '^(?=.*\S).{20,}$'
          bodyPatternError: |
            The pull request body should contain at least 20 meaningful characters with a clear description.
            
            Please provide:
            - **What**: Clear description of changes made
            - **Why**: Explanation of why these changes were necessary  
            - **How**: Brief overview of the approach taken (if complex)
            - **Testing**: Information about testing performed
            
            Example:
            ```
            ## What
            Add JWT authentication system to secure API endpoints.
            
            ## Why  
            Current authentication system has security vulnerabilities.
            
            ## Testing
            - Added unit tests for JWT utilities
            - Tested login/logout flows manually
            ```
            
            See CONTRIBUTING.md for detailed PR standards.
          # Skip validation for certain labels
          ignoreLabels: |
            dependencies
            automated-pr